Add `pb_read` and `pb_write` functions
ropensci/piggyback pull request #115
Opened 2023-12-27 23:37 UTC by tanho63

Closes #97

2023-12-29 18:11 UTC, cboettig requested changes
this strategy (specifically the `guess_read_function()`) always makes me nervous.  While all abstractions are a bit leaky, I've always found attempts to write a generic "read" function as an abstract method particularly leaky.  There's just too much going on in `read_` methods to abstract away (what about other data serializations, like spatial formats? what about lazy reads / remote reads etc).  

I'm fine with a convenience wrapper that makes common use patterns more concise.  Maybe all that's needed is a bit more documentation saying something like 'for common formats such as ...`, along with advice about how to bypass this convenience if a user prefers their own read function (say, from `readr` package, or for some other format).

2023-12-29 19:31 UTC, tanho63 commented
> too much going on in read_ methods to abstract away (what about other data serializations, like spatial formats? 

I believe this will fail on spatial formats since it would not be one of csv, tsv, rds, parquet? (unfamiliar with how geoparquet works and whether arrow::read_parquet will process geoparquet, but I assume yes?). 

> what about lazy reads / remote reads etc?

Yep, this will read eagerly by design/default, and maybe it's a bad thing for folks who should be thinking about optimizing - however uninformed users would currently do pb_download anyways so it's not necessarily much different than that? 

I agree with improving the docs, e.g. 
- explaining that cloud native is best performance (more clearly linking to vignette)
- demonstrating ways to read from URL (maybe adding to getting started vignette?)
- better demonstrating examples of passing in a different read function and explaining what is supported ?

2023-12-30 05:03 UTC, tanho63 commented on R/pb_read.R
> +#' @param .token GitHub authentication token, see [gh::gh_token()]
Fleshed out more of this section, explaining how the read_function will be used (file as first arg etc)

2023-12-30 05:04 UTC, tanho63 commented on R/pb_read.R
> +#' @keywords internal
`guess_read_function` also gets a man page with explicit mappings

2023-12-30 05:04 UTC, tanho63 commented on R/pb_write.R
> +    "tsv" = function(x, file, ..., sep = "\t") utils::write.csv(x = x, file = file, sep = sep, ...),
I don't use tsvs a lot, is there a better tsv writing function I don't know about?

2023-12-30 05:05 UTC, tanho63 commented on vignettes/piggyback.Rmd
> +
in progress, will finish later this weekend hopefully. 

Will try to add examples of reading URLs above, and then will demonstrate pb_read/write below including how to pass it other read_functions.

2023-12-30 18:20 UTC, tanho63 commented on vignettes/piggyback.Rmd
> +close(pb_url)
@cboettig started writing out this "how to download from URL" section and I feel like this got really complicated really quickly. This makes me think we should have a pb_read_url but, unlike with just downloading it to disk, URL support is more complicated especially if we want to abstract the authentication for them:

- base R stuff tends to accept plain URLs and `url()` except `readRDS` which only works with `url()`
- jsonlite supports a url() connection or plain URL
- arrow doesn't accept a `url()` connection but instead wants the plain URL or a raw vector, so we would need to curl it first to pass the auth headers

```r
guess_read_url_function <- function(file) {
  switch(
    file_extension,
    "csv" = function(url, ..., headers) {con<-url(url, headers = headers); on.exit(close(con)); read.csv(con,...)},
    "rds" = function(url, ..., headers) {con<-url(url, headers = headers); on.exit(close(con)); readRDS(con,...)},
    "parquet" = function(url, ..., headers) {httr::GET(url, headers = headers)$content %>% read_parquet(...)},
    stop("unknown fmt")
)
```

2023-12-30 18:22 UTC, tanho63 commented on vignettes/piggyback.Rmd
> +5. The `use_timestamps` argument defaults to TRUE - notice that above,
noticed while explaining this that use_timestamps and overwrite are not merged as they are in pb_upload, raised new issue in #119

2023-12-30 18:30 UTC, tanho63 commented on vignettes/piggyback.Rmd
> +close(pb_url)
two paths-ish forward: 

A) tell users to just go to `pb_read` for simplicity if the repo is private
B) make `pb_read_url` happen

I'm ambivalent between the two and unsure how much difference in performance there actually is between pb_read and hypothetical pb_read_url paths...actually I can test that:

2023-12-30 18:38 UTC, tanho63 commented on vignettes/piggyback.Rmd
> +close(pb_url)
alright this surprises the heck out of me:

```r
# A tibble: 5 × 13                                                                                   
#> expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time 
#> <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> 
#>   1 pb_read       193ms    206ms      4.90  265.87KB     0        5     0      1.02s 
#>   2 read.csv      603ms    618ms      1.57  147.84KB     0        5     0      3.18s 
#>   3 read_csv      427ms    454ms      2.25    2.09MB     1.50     3     2      1.34s 
#>   4 fread         140ms    143ms      6.50   33.86KB     0        5     0   769.03ms 
#>   5 arrow         604ms    620ms      1.57    2.02MB     0        5     0      3.18s 
```

2023-12-30 18:44 UTC, tanho63 commented on vignettes/piggyback.Rmd
> +close(pb_url)
Attempting with larger size...

```r
options(piggyback.verbose = FALSE)
bench::mark(
  pb_read = pb_read("play_by_play_2023.csv", repo = "nflverse/nflverse-data", tag = "pbp"),
  read.csv = read.csv(pb_download_url("play_by_play_2023.csv", repo = "nflverse/nflverse-data", tag = "pbp")),
  read_csv = readr::read_csv(pb_download_url("play_by_play_2023.csv", repo = "nflverse/nflverse-data", tag = "pbp")),
  fread = data.table::fread(pb_download_url("play_by_play_2023.csv", repo = "nflverse/nflverse-data", tag = "pbp")),
  check = FALSE,
  min_iterations = 2
)
#> # A tibble: 4 × 13                                                               
#> expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time
#> <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm>
#>   1 pb_read       7.51s    7.62s     0.131     583MB    0.787     2    12     15.24s
#> 2 read.csv      5.52s    5.97s     0.168     582MB    0.838     2    10     11.93s
#> 3 read_csv      4.54s    5.64s     0.177     200MB    0.266     2     3     11.28s
#> 4 fread         3.99s    4.13s     0.242     215MB    0.484     2     4      8.27s
```
okay, phew, must have been overhead or something

2023-12-30 19:48 UTC, tanho63 commented on vignettes/piggyback.Rmd
> +close(pb_url)
Opted for option 1 so that I don't have to implement pb_read_url right away. This PR got away from me again...

2023-12-30 20:33 UTC, tanho63 commented
Flow state hit me like a bus, many apologies for this PR running away from me. Since your last review ([diff](https://github.com/ropensci/piggyback/pull/115/files/6ff7768a3a148d6b6c7dfc58821bd193a8cfa08b..8f8d08d622f5655dedd90c49d8d23f42cee894c1)), I:
- gitignored/got rid of the stored docs/ folder because ropensci pkgdown externally + I've been using it to test out how the vignette looks after generating it
- updated DESCRIPTION with the newly shortened description from the readme (because I realized it hadn't been updated)
- fleshed out man files for read_function and write_function args, added man files for guess_read_function and guess_write_function that fully explain how it gets mapped
- added various \dontshow blocks to hide the interactive() and try() blocks as inspired by the examplesIf 
- updated README to not evaluate any chunks except for regenerating codemeta (improves syntax highlighting in RStudio to use {r} instead of just r)
- rewrote vignette/piggyback.Rmd again to try and address your various feedback points - this is probably the [main thing](https://github.com/ropensci/piggyback/pull/115/files/6ff7768a3a148d6b6c7dfc58821bd193a8cfa08b..8f8d08d622f5655dedd90c49d8d23f42cee894c1#diff-795726fefb581909ff7dbfcc9a68590b225463c8b0836491f99652ac6c810981) that needs looked at

2023-12-30 23:11 UTC, cboettig approved these changes
looks good!

2023-12-30 23:26 UTC, merged